name: Reddit Docker Image Deployment

on:
  push:
    branches:
      - main
      - STM-180

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64/v8

    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.0
      with:
        submodules: recursive
        token: ${{ secrets.REPO_WORKFLOW_PAT }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker image tags
      id: meta
      uses: docker/metadata-action@v3.0.0
      with:
        images: sentmint/r-scrape

    - name: Build and push
      uses: docker/build-push-action@v5.0.0
      with:
        push: true
        platforms: ${{ matrix.platform }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: .
        file: ./reddit/Dockerfile


